### ISSUE TITLE
Wrong linux nrfutil URLs in package_neoPLC_index.json

### ISSUE THREAD

**Issue by llanphar** [DeftDynamics/neoPLC-arduino#2]
[package_neoPLC_index.json](https://deftdynamics.github.io/neoPLC-arduino/package_neoPLC_index.json) contains the following entries for nrfutil:

```
            {
              "host": "i686-linux-gnu",
              "url": "https://github.com/DeftDynamics/neoPLC-arduino/releases/download/tools/nrfutil-mac.tar.gz",
              "archiveFileName": "nrfutil-linux.tar.gz",
              "size": "4558668",
              "checksum": "MD5:403b0f83b6fabb146a12526e7c7009e9"
            },
            {
              "host": "x86_64-pc-linux-gnu",
              "url": "https://github.com/DeftDynamics/neoPLC-arduino/releases/download/tools/nrfutil-mac.tar.gz",
              "archiveFileName": "nrfutil-linux.tar.gz",
              "size": "4558668",
              "checksum": "MD5:403b0f83b6fabb146a12526e7c7009e9"
            },
```
Note the `nrfutil-mac.tar.gz` part--when trying to install the board in linux Arduino IDE it downloads the mac tarball instead of the linux one and throws a CRC error.

**Comment by llanphar** [comment]
I made a copy of the json file and manually corrected it. The install gets further along but then bails with this:
```
Invalid archive: it must contain a single root folder
java.lang.RuntimeException: java.io.IOException: Invalid archive: it must contain a single root folder
	at cc.arduino.contributions.packages.ui.ContributionManagerUI.lambda$onInstallPressed$1(ContributionManagerUI.java:176)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.IOException: Invalid archive: it must contain a single root folder
	at cc.arduino.utils.ArchiveExtractor.extract(ArchiveExtractor.java:167)
	at cc.arduino.utils.ArchiveExtractor.extract(ArchiveExtractor.java:81)
	at cc.arduino.contributions.packages.ContributionInstaller.install(ContributionInstaller.java:142)
	at cc.arduino.contributions.packages.ui.ContributionManagerUI.lambda$onInstallPressed$1(ContributionManagerUI.java:173)
	... 1 more
```
The directory structure on `nrfutil-linux.tar.gz` is different from the other two tarballs:
```
llanphar@lenlaptop:~/src/neoPLC-arduino$ tar tf nrfutil-win32.tar.gz 
nrfutil/
nrfutil/nrfutil.exe
llanphar@lenlaptop:~/src/neoPLC-arduino$ tar tf nrfutil-mac.tar.gz 
nrfutil/
nrfutil/nrfutil
llanphar@lenlaptop:~/src/neoPLC-arduino$ tar tf nrfutil-linux.tar.gz 
nrfutil
llanphar@lenlaptop:~/src/neoPLC-arduino$ 

```

**Comment by DeftDynamics** [comment]
sorry for the late response on this, we've updated the linux tarball and package file. Hopefully this resolves the issue, but please let us know if you run into any more trouble.
